# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: ""                                # Your name
  description: "Julio is a renowned wizard and scholar of Middle-earth"   # A brief slogan (optional)
  image: img/my_image.jpg
  favicon: img/favicon.png
  # start of the navigation bar at the top of the website
  navbar:
    pinned: false
    logo: /img/logo2.png
    background: "#A14593"
    # your sub-pages
    left:
      - text: "About"
        href: about/index.qmd
      - text: "Board"
        href: board/index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Publications"
        href: projects/papers.qmd                  
      - text: "Activities"
        href: news/index.qmd
      - text: "Newsletter"
        href: https://google.com    
      - text: "Links"
        href: links/index.qmd
    
    # your social media handles
    right:
      # - icon: folder-symlink
      #   href: https://www.marvinschmitt.com/blog/website-tutorial-quarto/
      # - icon: twitter
      #   href: https://twitter.com/MarvinSchmittML
      # - icon: linkedin
      #   href: https://www.linkedin.com/in/marvin-schmitt-a85b321a2/
      - icon: envelope
        aria-label: email
        href: "mailto:mail.marvinschmitt@gmail.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Julio Iturra-Sanhueza CC BY-SA 4.0</span>
#    center: |
#      <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template!</a></span>
    right: |
      <span class="faux-block"><a href="https://github.com/jciturras/isa-rc42">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    highlight-style: github-dark #change text from code chunks to white. 
    smooth-scroll: true
    include-in-header: meta.html
    theme: 
          light: pulse
          dark: cyborg
          
    css: styles.css
    toc: true
    code-link: true
    link-external-newwindow: true 
    citations-hover: true
    footnotes-hover: true
editor: visual
